project:
  type: website
  output-dir: docs

website:
  title: "SC"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: blog/index.qmd
        text: Blog


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



