---
title: ¿Cómo la IA mejora las búsquedas online?
---

Para mostrar resultados relevantes los motores de búsqueda tradicionales se basan principalmente en el uso de palabras clave. Por ejemplo, si yo busco “una silla blanca” en un sitio de muebles voy a encontrar productos que contienen la palabra “silla” y la palabra “blanca”. Los resultados van a ser algo del estilo “Silla de comedor moderna blanca”, “Silla cómoda blanca”, etc. Pero si busco “muebles de sala para un espacio pequeño” seguramente no obtenga ningún resultado porque ningún nombre de mueble contiene estas palabras exactamente. Entender lo que el usuario busca sin que lo diga explícitamente es una tarea que muchos motores de búsqueda no logran. En este artículo voy a hablar de cómo dos empresas logran entender lo que el usuario busca con IA, cambiando así la manera en la que los usuarios descubren productos en línea. 

La búsqueda semántica (o semantic search en inglés) corresponde a la idea de buscar ítems relevantes a una consulta basándose en el significado de la consulta en lugar de una correspondencia con palabras clave. Aunque ciertos métodos que permiten “entender” la intención del usuario ya existían, con la IA es posible tener resultados de mejor calidad. 

Un ejemplo de esto es [Roomix](https://roomix.ai). Normalmente para buscar un apartamento los criterios que nos ofrecen las plataformas están predefinidos. Por ejemplo, uno puede seleccionar un rango de metros cuadrados, el número de dormitorios y un área geográfica en específico. Sin embargo, uno no puede buscar en función de algo que no esté en los filtros del motor de búsqueda como el estilo del apartamento. Roomix es una plataforma argentina que permite, entre otros, buscar propiedades a través de una descripción visual. Esto da posibilidad de buscar por estilo (como “apartamento moderno”), descripciones de espacios (como “jardín amplío”) o incluso materiales (como “pisos de madera”). Sin esta tecnología, la única alternativa para los usuarios que priorizan criterios estéticos es navegar a mano todo el catálogo. 

Otro ejemplo es Spotify que progresivamente ha integrado capacidades para buscar música con lenguaje natural. En lugar de buscar el título de una canción en específico, ahora también es posible buscar según descripciones como “canciones que suenan como X artista pero más tranquilas”. Es importante notar cómo en este caso en particular el enfoque tradicional de comparar palabras clave con descripciones y títulos no es pertinente. Criterios como “tranquila” se traducen en un ritmo más lento y descripciones como “que suena a” corresponden al género. Sin embargo, ninguno de estos criterios se ve reflejado necesariamente en el título de la canción. En este caso, el hecho de no encontrar lo que uno busca no significa necesariamente perder una compra para Spotify, pero sí significa degradar la experiencia del usuario. 

Dicho esto, los motores de búsqueda tradicionales pueden crear puntos ciegos en cualquier rubro : tiendas de ropa que no entienden cuando un usuario busca un look casual, ferreterías que no entienden cuando un usuario busca la pieza que va entre el grifo y la manguera, tiendas de muebles que no entienden cuando un usuario busca un sofá apto para mascotas, etc. Incluso si un comercio ofrece lo que el usuario busca, la compra no se llevará a cabo si el usuario no lo encuentra. En mi opinión, las búsquedas con lenguaje natural van a volverse progresivamente la norma. Tener lo que el usuario busca es solo una parte del problema. La otra parte es lograr que el usuario lo encuentre y la IA está facilitando este proceso. 

Sixto :) 
